### ISSUE TITLE
AppImage not running on Arch linux. Not sure about other distros. 

### ISSUE THREAD

**Issue by joeybronzoni** [Defdist/DDCut#1]
Hey -I got excited about seeing this AppImage hoping this would give me access to run DDCut on my Linux box. I've tried versions: 
**DDCut-V-5.1.7.AppImage, DDCut-V-5.1.6.AppImage, and DDCut-V-5.1.5.AppImage** 
and all three fail. To reproduce download Appimage, **chmod** to be executable and execute the file and it opens up a blank white window for a moment and fails with this error: 
``` 
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    2922172 abort (core dumped)  ./DDCut-V-5.1.6.AppImage
``` 
I've seen some issue with fontconfig on other apps in the past but I wouldn't say that's the only thing here with the std::bad_alloc issue. I obviously don't know for sure but I'd love some help getting this running on my Linux box. Thanks.

*On **Ubuntu 18.04** i get this error when running the AppImages: 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /tmp/.mount_DDCut-GpHuuR/resources/app/app/Backend/ddcut.node: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_DDCut-GpHuuR/resources/app/app/Backend/ddcut.node)
    at Object.<anonymous> (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:1047)
    at Object.14 (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:1085)
    at n (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:110)
    at Module.15 (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:1614)
    at n (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:110)
    at Module.65 (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:8604)
    at n (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:110)
    at /tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:902
    at Object.<anonymous> (/tmp/.mount_DDCut-GpHuuR/resources/app/app/index.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
```

I've tried a few things and even with the fontconfig error gone I still get that issue of 
``` 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    2922172 abort (core dumped)
``` 
But honestly I have no real idea about anything without knowing what's under the hood with the source code etc.

**Comment by joeybronzoni** [comment]
I see you have a docker container for this as well. I have no idea about this project as I am literally just getting into DDcut today. But I wanted to mention that if this project isn't dead I'd like to help in any way I can. I don't do any of my work on github anymore as you can see from my profile pic but I do use docker and am starting to use Kubernetes at work yada yada yada -I'd like to help let me know thanks.

**Comment by natedennis** [comment]
There is more than one of us. Avid linux user of 20+ years/ professional dev. Looked at the design of the GG1 and GG2 machines.. but never got behind this effort because im simply not fighting wine to use DDCut. So I built my design out of aluminum, wrote my own GCODE, (i did steal a couple of your probe routines). Ive been using UGS to control my uno and cnc shield. FreeCAD to generate my paths (dont laugh.. im cheap though i have it.. im not using cloud anything for this) Only ruined 2 lowers in that effort. but thats just 20% of the way there. We all know whats coming and while one of my machines is much larger.. rigidity is a problem. I want from a block of metal.  And i already work 80 hours a week and dont have the time to invest generating all these paths and designing jigs to hold stuff. And it just so happened i know i guy that has a v3 for sale. Adding another machine to the shop isnt going to break my heart. When i heard you guys were working on 0% and a linux versions you have my attention. Your source folders are empty. I cant help unless its open sourced. There may be very obvious reasons you arent doing that on this platform. And i get it,, but you guys dont have to be alone in this effort. There are those that lurk around watching that do this stuff just because we can. leverage the those guys and lets go farther. 

i said all that to say this.. the above error that i am also getting on arch on the most recent version is normally a **Memory allocation failure**

**Comment by shiruken1** [comment]
Here's what I get:

```
$./DDCut-V-5.2.1.AppImage 

(ddcut:3266739): Gtk-WARNING **: 08:59:44.969: Theme parsing error: gtk.css:2:14: Not using units is deprecated. Assuming 'px'.

(ddcut:3266739): Gtk-WARNING **: 08:59:44.969: Theme parsing error: gtk.css:2:16: Not using units is deprecated. Assuming 'px'.

(ddcut:3266739): Gtk-WARNING **: 08:59:44.969: Theme parsing error: gtk.css:2:18: Not using units is deprecated. Assuming 'px'.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by sdaves** [comment]
I may have found the root cause.

https://github.com/nodejs/help/issues/2414

Looks like GCC-9 needs to be used:

    export CXX="g++-9" CC="gcc-9";

@defdistadmin @bb-msf-dd @ryantoll Can you rebuild with this set and share the AppImage?

**Comment by mploschiavo** [comment]
Any update on linux progress? Might be nice to run on a raspberry pi with linux
